# Generated by Django 3.2.9 on 2021-12-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('imageLink', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('roundNo', models.IntegerField(default=1)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
