# Generated by Django 3.2.9 on 2021-12-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_leaderboard_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='profile',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='picture',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
