# Generated by Django 3.2.9 on 2021-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211209_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
