# Generated by Django 3.2.9 on 2021-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
