# Generated by Django 3.2.9 on 2021-12-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_leaderboard_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('picture', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(default='', max_length=50)),
                ('teamCode', models.CharField(default='', max_length=6, unique=True)),
                ('teamLevel', models.PositiveIntegerField(default=1)),
                ('teamScore', models.IntegerField(default=0)),
                ('teamLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamLeader', to='api.player')),
                ('teamPlayerOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamPlayerOne', to='api.player')),
                ('teamPlayerTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamPlayerTwo', to='api.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
