# Generated by Django 3.2.9 on 2021-12-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211212_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleaderboard',
            name='teamCode',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
