# Generated by Django 3.2.9 on 2021-12-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_player_isteamed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleaderboard',
            name='teamPlayerOne',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamPlayerOne', to='api.player'),
        ),
        migrations.AlterField(
            model_name='teamleaderboard',
            name='teamPlayerTwo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamPlayerTwo', to='api.player'),
        ),
    ]
